### PR TITLE
Allow interop between Firefox and Chrome

### PR DESCRIPTION
**Pull request by nathanoehlman**
This fixes an interop issue between Firefox and Chrome, namely, in the case where Firefox was the offerer, and Chrome the answerer.

Chrome would attempt to process the ICE candidates prior to the remote description being set, resulting in the failure to apply the candidate.

The priorities of the tasks should now reflect the expected flow.

### CODE REVIEW

**Comment by nathanoehlman** [comment]
@DamonOehlman Any thoughts on this? The change seems to restore Firefox <-> Chrome interoperability but if you can remember - was there any particular reason behind the original ordering that might cause issues?

**Comment by DamonOehlman** [comment]
@nathanoehlman Looks good.  But I think what is happening now is starting to herald the potential end of the `rtc-taskqueue` package's usefulness.  With firefox taking WebRTC seriously now, and the browsers doing a better job of ensuring they are in the appropriate ready state (or deferring operations) until they are I think you should probably look at resimplifying `rtc-tools`.  This may well mean deprecating and removing `rtc-taskqueue`.

Also, I know bandwidth is tight, but I think interop tests are probably becoming a higher priority again.  I'm still hoping that @thepatrick will manage to get permission what Tokbox have been using behind the scenes, so that it can be used by others :)

**Comment by nathanoehlman** [comment]
@DamonOehlman Yep - I agree, I think returning to a simpler implementation is definitely going to have to be on the roadmap for the near future - I'll see if I can find some time at some point

**Comment by silviapfeiffer** [comment]
Microsoft edge just released ortc support - more shims necessary.

**Pull request merged**
