### PR TITLE
Don't parse sdp in case of empty sdpMid value

### PR DESCRIPTION
**Pull request by vkosh**
I've noticed a large performance impact on parsing sdp in isConnReadyForCandidate: chrome/firefox on >30 peers gives 100% of one cpu core usage on intel core-i3. Disabling isConnReadyForCandidate in my app gives ~25% cpu usage under the same conditions.
This commit tries to avoid parsing of sdp if possible.

### CODE REVIEW

**Comment by DamonOehlman** [comment]
@vkosh Thanks for the heads up on this.  Sounds like I need to dig into this performance issue in a bit more depth. With the change you have made here do you notice an improvement?

**Comment by vkosh** [comment]
Well, actually I can't say confidently that the patch gives an improvement because it's hard to reproduce the same conditions on each app run. It would great to implement partial sdp parsing to detect if given sdpMid contains in sdp's media types.

**Comment by vkosh** [comment]
I think there's another way of optimization. The task queue checks called on every orderTasks and checkQueue call. But do we really need to parse sdp so many times and recheck if candidate is valid? Correct me if I'm wrong, but I think the task checks may be divided into static (calculated once and cached, e.g. hasLocalOrRemoteDesc, isValidCandidate, isConnReadyForCandidate) and dynamic ones (isNotClosed). Also the task priority may be set once at queue.enq.

**Comment by DamonOehlman** [comment]
@vkosh Absolutely not.  That was my thinking to - given that sdp parsing is expensive it should be done once and only once.  It might be a few days before I get a chance to look at this, but I'd prefer to see this kind of functionality implemented rather than a workaround.  If you would like to open another PR in the meantime with those changes that would be most welcome.

**Comment by vkosh** [comment]
Implemented in https://github.com/rtc-io/rtc-taskqueue/pull/9

**Pull request closed without merging**
