### PR TITLE
Queue optimizations

### PR DESCRIPTION
**Pull request by vkosh**
This opimizes rtc task queue handling by caching results of sdp parsing and task priority initialization. It gives major performance gain even without https://github.com/rtc-io/rtc-tools/issues/37

### CODE REVIEW

**Comment by DamonOehlman** [comment]
@nathanoehlman - can I leave these to you to review and merge this and @vkosh other PRs please?

@silviapfeiffer - Did you ever resolve whether the CLA was required or not?  I know that was something that was being discussed before I moved on from NICTA, but wasn't sure of the outcome.

@vkosh - Thanks for the contribution to the project! :cake:

**Comment by nathanoehlman** [comment]
@vkosh Thanks for the pull requests! 2.6.1 has been published containing this and #10

**Comment by vkosh** [comment]
@DamonOehlman @nathanoehlman Thanks for managing this. Would you have a look at https://github.com/rtc-io/rtc-tools/issues/37 which is a main performance blocker.

**Comment by silviapfeiffer** [comment]
So, this has actually made our app quite unstable: stops peers from connecting and delays connecting quite a bit. Sorry to have to say, but I'd be in favor of pulling this patch at this point in time, actually.

**Comment by DamonOehlman** [comment]
@nathanoehlman @silviapfeiffer Is it possible to replicate the conditions that are causing app instability in a test somehow?  It would be great to know that people like @vkosh can make changes to the project without having to worry about breaking things upstream.

The tests here have always been a bit light on, and was one of the reasons I created higher level packages that tested more of the breadth of rtc.io (such as [`rtc-quickconnect-test`](https://www.npmjs.com/package/rtc-quickconnect-test)).  The only trick now is to work out how to have that package resolve references to `rtc-taskqueue` to the host package rather than attempting to resolve it through it's own dependency tree.

Something I'll have a think about.  It's possible while the in progress version satisfies the version required by the `rtc-quickconnect-test` tree it will use the local, but it would need to be confirmed...

**Comment by DamonOehlman** [comment]
Unfortunately it's not good news on the dependency resolution front,  after doing a:

```
npm install rtc-quickconnect-test rtc-quickconnect --save-dev
```

in the `rtc-taskqueue` project dir, this was the result of a `npm ls rtc-taskqueue`:

```
rtc-taskqueue@2.6.3 /home/damo/code/rtc.io/rtc-taskqueue
└─┬ rtc-quickconnect@4.3.1
  └─┬ rtc-tools@4.2.5
    └── rtc-taskqueue@2.6.3 
```

**Comment by silviapfeiffer** [comment]
Yeah, sorry for that unhelpful comment. We will need to do some more testing to figure out exactly what is happening.

**Comment by nathanoehlman** [comment]
This is a tricky bug to to replicate in any form of local development environment.

My current thinking is that what is occurring is the following:
1. An initial WebRTC peer connection is established between to remote clients (can't be local clients) using a viable ICE candidate, which all works with the cached media types
2. The PeerConnection remains in the ICE 'connected' state, indicating that while it has achieved a viable peer connection, it will continue to examine other candidates for a better candidate pair.
3. A better candidate pair is discovered, and the connection attempts to upgrade to the newer pair
4. The caching of the media types than causes an issue somehow with the upgrading of the connection to the new candidate pair and things break. 

@DamonOehlman If you've got any ideas about how to test this, I'd appreciate any suggestions

**Comment by vkosh** [comment]
I think this may be related to https://github.com/rtc-io/rtc-tools/issues/37 (solved in https://github.com/rtc-io/rtc-tools/pull/38) somehow. All of candidates apply to _all_ of peer connections which causes connections upgrade.
BTW I've been using this PR with https://github.com/rtc-io/rtc-tools/pull/38 in production for two weeks and I haven't noticed any issues in peers coupling.

**Pull request merged**
